if !has('nvim')
	set term=xterm-256color
endif
set updatecount=0
set autoindent	
set smartindent
"set title
set tabstop=4	
set shiftwidth=0 
set scrolloff=5
set noloadplugins
set nohlsearch
set nonumber
set nocompatible
set noincsearch
set autoread
set showcmd
set showtabline=2
set laststatus=2
set wmh=0
set wmw=0
set backspace=2
set wrap
set comments=""
set iskeyword+=-
set shortmess+=A
set mouse=
filetype on
filetype indent plugin off
